### ISSUE TITLE
presentation.md is not used ?

### ISSUE THREAD

**Issue by paulgirard** [c24b/openscience4S#2]
Your presentation.md is almost empty where the presentation/openscience4S.html contains the real presentation.
Not sure to understand te use of presentation.md ?

Wich makes my original comments deprecated but I add it below for information : 

You can load your presentation.md directly in your reveal html page using this code in the slides tag:

``` html
      <div class="slides">

        <section data-markdown="./presentation.md"
                 data-separator="^==="
                 data-separator-vertical="^----"
                 data-separator-notes="^Note:"
                 data-charset="utf8">
        </section>

      </div>
```

**Comment by c24b** [comment]
Merci de cette remarque, en effet à l'origine nous avions pensé générer a partir du markdown la presentation depuis reveal-markdown. Mais au final, les options étaient plus restreintes en termes de mise en page, nous sommes donc passés à la version full html.

presentation.md est désormais supprimé pour ne pas induire en erreur.
